/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Authorbook;
import com.example.jooq.tables.Authors;
import com.example.jooq.tables.Books;
import com.example.jooq.tables.FlywaySchemaHistory;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTHORBOOK_PKEY = Indexes0.AUTHORBOOK_PKEY;
    public static final Index AUTHORS_PKEY = Indexes0.AUTHORS_PKEY;
    public static final Index BOOKS_PKEY = Indexes0.BOOKS_PKEY;
    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AUTHORBOOK_PKEY = Internal.createIndex("authorbook_pkey", Authorbook.AUTHORBOOK, new OrderField[] { Authorbook.AUTHORBOOK.AUTHOR_ID, Authorbook.AUTHORBOOK.BOOK_ID }, true);
        public static Index AUTHORS_PKEY = Internal.createIndex("authors_pkey", Authors.AUTHORS, new OrderField[] { Authors.AUTHORS.ID }, true);
        public static Index BOOKS_PKEY = Internal.createIndex("books_pkey", Books.BOOKS, new OrderField[] { Books.BOOKS.ID }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    }
}
