/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Authorbook;
import com.example.jooq.tables.Authors;
import com.example.jooq.tables.Books;
import com.example.jooq.tables.FlywaySchemaHistory;
import com.example.jooq.tables.records.AuthorbookRecord;
import com.example.jooq.tables.records.AuthorsRecord;
import com.example.jooq.tables.records.BooksRecord;
import com.example.jooq.tables.records.FlywaySchemaHistoryRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorbookRecord> AUTHORBOOK_PKEY = UniqueKeys0.AUTHORBOOK_PKEY;
    public static final UniqueKey<AuthorsRecord> AUTHORS_PKEY = UniqueKeys0.AUTHORS_PKEY;
    public static final UniqueKey<BooksRecord> BOOKS_PKEY = UniqueKeys0.BOOKS_PKEY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AuthorbookRecord, AuthorsRecord> AUTHORBOOK__FK_AB_AUTHOR = ForeignKeys0.AUTHORBOOK__FK_AB_AUTHOR;
    public static final ForeignKey<AuthorbookRecord, BooksRecord> AUTHORBOOK__FK_AB_BOOKS = ForeignKeys0.AUTHORBOOK__FK_AB_BOOKS;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AuthorbookRecord> AUTHORBOOK_PKEY = Internal.createUniqueKey(Authorbook.AUTHORBOOK, "authorbook_pkey", Authorbook.AUTHORBOOK.AUTHOR_ID, Authorbook.AUTHORBOOK.BOOK_ID);
        public static final UniqueKey<AuthorsRecord> AUTHORS_PKEY = Internal.createUniqueKey(Authors.AUTHORS, "authors_pkey", Authors.AUTHORS.ID);
        public static final UniqueKey<BooksRecord> BOOKS_PKEY = Internal.createUniqueKey(Books.BOOKS, "books_pkey", Books.BOOKS.ID);
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AuthorbookRecord, AuthorsRecord> AUTHORBOOK__FK_AB_AUTHOR = Internal.createForeignKey(com.example.jooq.Keys.AUTHORS_PKEY, Authorbook.AUTHORBOOK, "authorbook__fk_ab_author", Authorbook.AUTHORBOOK.AUTHOR_ID);
        public static final ForeignKey<AuthorbookRecord, BooksRecord> AUTHORBOOK__FK_AB_BOOKS = Internal.createForeignKey(com.example.jooq.Keys.BOOKS_PKEY, Authorbook.AUTHORBOOK, "authorbook__fk_ab_books", Authorbook.AUTHORBOOK.BOOK_ID);
    }
}
