/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Authorbook;
import com.example.jooq.tables.Authors;
import com.example.jooq.tables.Books;
import com.example.jooq.tables.FlywaySchemaHistory;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.authorbook</code>.
     */
    public static final Authorbook AUTHORBOOK = com.example.jooq.tables.Authorbook.AUTHORBOOK;

    /**
     * The table <code>public.authors</code>.
     */
    public static final Authors AUTHORS = com.example.jooq.tables.Authors.AUTHORS;

    /**
     * The table <code>public.books</code>.
     */
    public static final Books BOOKS = com.example.jooq.tables.Books.BOOKS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.example.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
