version: '3.1'

services:
  local-postgre-db:
    container_name: local-postgre-db
    image: postgres:9.6.9
    environment:
      POSTGRES_DB: public
      POSTGRES_USER: sa
      POSTGRES_PASS:
    expose:
    - 5450
    ports:
    - 5450:5432
    restart: unless-stopped