/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authorbook implements Serializable {

    private static final long serialVersionUID = -1921678543;

    private final Integer authorId;
    private final Integer bookId;

    public Authorbook(Authorbook value) {
        this.authorId = value.authorId;
        this.bookId = value.bookId;
    }

    public Authorbook(
        Integer authorId,
        Integer bookId
    ) {
        this.authorId = authorId;
        this.bookId = bookId;
    }

    public Integer getAuthorId() {
        return this.authorId;
    }

    public Integer getBookId() {
        return this.bookId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Authorbook other = (Authorbook) obj;
        if (authorId == null) {
            if (other.authorId != null)
                return false;
        }
        else if (!authorId.equals(other.authorId))
            return false;
        if (bookId == null) {
            if (other.bookId != null)
                return false;
        }
        else if (!bookId.equals(other.bookId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.authorId == null) ? 0 : this.authorId.hashCode());
        result = prime * result + ((this.bookId == null) ? 0 : this.bookId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Authorbook (");

        sb.append(authorId);
        sb.append(", ").append(bookId);

        sb.append(")");
        return sb.toString();
    }
}
